namespace master.framework.attribute.database
{
    public class Key : System.Attribute
    {
        public bool AutoGenerated { get; set; }
        public Key(bool autoGenerated = false)
        {
            AutoGenerated = autoGenerated;
        }
    }
}
